import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3, MapPin, Minus, Plus, ShoppingBag, Truck } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import { formatRupiah, products } from "@/data/catalog";
import { useCart } from "@/contexts/CartContext";

export default function ProductDetail() {
  const [, params] = useRoute("/produk/:id");
  const [, navigate] = useLocation();
  const product = products.find((item) => item.id === params?.id) ?? products[0];
  const [quantity, setQuantity] = useState(1);
  const { addItem } = useCart();
  const addToCart = () => { Array.from({ length: quantity }).forEach(() => addItem(product)); toast.success("Ditambahkan ke keranjang", { description: product.name }); navigate("/"); };
  return <div className="app-shell detail-shell"><header className="site-header"><div className="container-wide header-inner"><Link href="/" className="brand"><span className="brand-mark">P</span><span>PASAR<span>KU</span></span></Link><div className="detail-breadcrumb"><Link href="/">Beranda</Link><span>/</span><span>{product.category}</span><span>/</span><strong>Detail produk</strong></div><Link href="/" className="icon-button"><ShoppingBag size={18} /></Link></div></header><main className="detail-main"><div className="container-wide"><Link href="/" className="back-link"><ArrowLeft size={16} /> Kembali ke katalog</Link><div className="detail-grid"><div className={`detail-visual ${product.accent}`}><span className="detail-emoji">{product.emoji}</span><span className="detail-stamp">Produk contoh<br /><strong>PASARKU</strong></span></div><div className="detail-copy"><div className="eyebrow">{product.category} · {product.badge}</div><h1>{product.name}</h1><div className="detail-vendor"><div className="vendor-avatar">{product.vendor.charAt(0)}</div><div><strong>{product.vendor}</strong><span><MapPin size={13} /> {product.location}</span></div><span className="verified"><Check size={13} /> Dikurasi admin</span></div><div className="detail-price">{formatRupiah(product.price)} <span>{product.unit}</span></div><p className="detail-description">{product.description}</p><div className="delivery-box"><div><Truck size={17} /><span>Antar lokal</span><strong>{product.eta}</strong></div><div><Clock3 size={17} /><span>Pembayaran</span><strong>COD / transfer</strong></div></div><div className="detail-actions"><div className="quantity-control large"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={16} /></button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)}><Plus size={16} /></button></div><button className="primary-button" onClick={addToCart}>Tambah ke keranjang <ArrowRight size={17} /></button></div><p className="detail-note"><Check size={15} /> Produk contoh untuk pratinjau. Detail akan disesuaikan setelah data UMKM dikumpulkan.</p></div></div><div className="related-section"><div className="section-heading"><div><div className="eyebrow">Mungkin Anda suka</div><h2>Pilihan lain di sekitar</h2></div><Link href="/" className="text-link dark-link">Lihat semua <ArrowRight size={15} /></Link></div><div className="mini-products">{products.filter((item) => item.id !== product.id).slice(0, 3).map((item) => <Link key={item.id} href={`/produk/${item.id}`} className="mini-product"><span className={`mini-thumb ${item.accent}`}>{item.emoji}</span><span><strong>{item.name}</strong><small>{formatRupiah(item.price)}</small></span><ArrowRight size={15} /></Link>)}</div></div></div></main></div>;
}
